# This file was generated by claude.

from std.ffi import OwnedDLHandle
from std.memory import UnsafePointer
from keyboard import Keyboard

@fieldwise_init
struct SDL_Rect:
    var x: Int32
    var y: Int32
    var w: Int32
    var h: Int32

struct SDL:
  var handle: OwnedDLHandle
  var window: Int
  var renderer: Int

  def __init__(out self) raises:
    self.handle = OwnedDLHandle("libSDL2.so")
    _ = self.handle.call["SDL_Init", Int32](UInt32(0x00000020))
    self.window = self.handle.call["SDL_CreateWindow", Int](
        "Chip-8".unsafe_ptr(),
        Int32(100), Int32(100),
        Int32(640), Int32(320),
        UInt32(0x00000004),
    )
    self.renderer = self.handle.call["SDL_CreateRenderer", Int](
        self.window, Int32(-1), UInt32(0)
    )



  def render(mut self, pixels: List[Bool]):
      # Background
      _ = self.handle.call["SDL_SetRenderDrawColor", Int32](
          self.renderer, UInt8(0), UInt8(0), UInt8(0), UInt8(255)
      )
      _ = self.handle.call["SDL_RenderClear", Int32](self.renderer)
      # Draw color
      _ = self.handle.call["SDL_SetRenderDrawColor", Int32](
          self.renderer, UInt8(255), UInt8(255), UInt8(255), UInt8(255)
      )
      # Draw every pixel as 10x10
      for y in range(32):
          for x in range(64):
              if pixels[y * 64 + x]:
                  var rect = SDL_Rect(
                      Int32(x * 10),   # x-Pos
                      Int32(y * 10),   # y-Pos
                      Int32(10),       # width
                      Int32(10),       # height
                  )
                  var rect_ptr = UnsafePointer(to=rect)
                  _ = self.handle.call["SDL_RenderFillRect", Int32](
                      self.renderer, rect_ptr
                  )
      # draw
      self.handle.call["SDL_RenderPresent"](self.renderer)
      self.handle.call["SDL_Delay"](UInt32(2))
    
  def pump_events(mut self):
      self.handle.call["SDL_PumpEvents"]()

  def poll_events(mut self, mut keyboard: Keyboard):
      var event = List[UInt8](length=56, fill=0)
      var event_ptr = UnsafePointer(to=event[0])

      while self.handle.call["SDL_PollEvent", Int32](event_ptr) != 0:
          var event_type = Int32(event[0]) | (Int32(event[1]) << 8) | (Int32(event[2]) << 16) | (Int32(event[3]) << 24)
          var scancode = Int32(event[16]) | (Int32(event[17]) << 8) | (Int32(event[18]) << 16) | (Int32(event[19]) << 24)

          # Key Mapping: SDL Scancode → Chip-8 Key
          var chip8_key: Int32 = -1
          if scancode == 30: chip8_key = 1      # 1
          elif scancode == 31: chip8_key = 2    # 2
          elif scancode == 32: chip8_key = 3    # 3
          elif scancode == 33: chip8_key = 0xC  # 4
          elif scancode == 20: chip8_key = 4    # Q
          elif scancode == 26: chip8_key = 5    # W
          elif scancode == 8: chip8_key = 6     # E
          elif scancode == 21: chip8_key = 0xD  # R
          elif scancode == 4: chip8_key = 7     # A
          elif scancode == 22: chip8_key = 8    # S
          elif scancode == 7: chip8_key = 9     # D
          elif scancode == 9: chip8_key = 0xE   # F
          elif scancode == 29: chip8_key = 0xA  # Z
          elif scancode == 27: chip8_key = 0    # X
          elif scancode == 6: chip8_key = 0xB   # C
          elif scancode == 25: chip8_key = 0xF  # V

          if chip8_key != -1:
              if event_type == 0x300:  # KEYDOWN
                  keyboard.key_down(UInt8(chip8_key))
              elif event_type == 0x301:  # KEYUP
                  keyboard.key_up(UInt8(chip8_key))

          if event_type == 0x100:  # SDL_QUIT
              self.handle.call["SDL_Quit"]()
